#!/bin/bash

LIMIT=""
START_EPOCH=""
END_EPOCH=""
USER_FILTER=""

while [ $# -gt 0 ]; do
    case "$1" in
        -n)
            LIMIT="$2"
	    ! [ "$LIMIT" -eq "$LIMIT" ] 2>/dev/null && { echo "Limita invalida"; exit 1; }
            shift 2
            ;;
        -p)
            USER_FILTER="$2"
	    [ -z "$USER_FILTER" ] && { echo "User invalid"; exit 1; }
            shift 2
            ;;
        -s)
		[ -z "$2" ] && { echo "Data start invalida"; exit 1; }
            START_EPOCH=$(date -d "$2" +%s 2>/dev/null)
            [ -z "$START_EPOCH" ] && { echo "Data start invalida"; exit 1; }
            shift 2
            ;;
        -t)
		[ -z "$2" ] && { echo "Data end invalida"; exit 1; }
            END_EPOCH=$(date -d "$2" +%s 2>/dev/null)
            [ -z "$END_EPOCH" ] && { echo "Data end invalida"; exit 1; }
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

read_logs() {
    for file in /var/log/auth.log*; do
        if [[ "$file" == *.gz ]]; then
            zcat "$file"
        else
            cat "$file"
        fi
    done
}
read_logs | while read -r line; do
    is_login=false
    user=""

    if [[ "$line" == *"sshd"* && "$line" == *"Accepted"* ]]; then
        user=$(echo "$line" | awk '{for(i=1;i<=NF;i++) if($i=="for"){print $(i+1)}}')
        is_login=true
    fi

    if [[ "$line" == *"systemd-logind"* && "$line" == *"New session"* && "$line" == *"of user"* ]]; then
        user=$(echo "$line" | awk '{for(i=1;i<=NF;i++) if($i=="user"){print $(i+1)}}' | tr -d '.')
        is_login=true
    fi

    [ "$is_login" = false ] && continue
    [ "$user" = "gdm" ] && continue

    log_time=$(echo "$line" | awk '{print $1}')
    echo "$user logged in at $log_time"
done
