#!/bin/bash

LIMIT=""
START_EPOCH=""
END_EPOCH=""
USER_FILTER=""

while [ $# -gt 0 ]; do
    case "$1" in
        -n)
            LIMIT="$2"
	    ! [ "$LIMIT" -eq "$LIMIT" ] 2>/dev/null && { echo "Limita invalida"; exit 1; }
            shift 2
            ;;
        -p)
            USER_FILTER="$2"
	    [ -z "$USER_FILTER" ] && { echo "User invalid"; exit 1; }
            shift 2
            ;;
        -s)
		[ -z "$2" ] && { echo "Data start invalida"; exit 1; }
            START_EPOCH=$(date -d "$2" +%s 2>/dev/null)
            [ -z "$START_EPOCH" ] && { echo "Data start invalida"; exit 1; }
            shift 2
            ;;
        -t)
		[ -z "$2" ] && { echo "Data end invalida"; exit 1; }
            END_EPOCH=$(date -d "$2" +%s 2>/dev/null)
            [ -z "$END_EPOCH" ] && { echo "Data end invalida"; exit 1; }
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

read_logs() {
    for file in /var/log/auth.log*; do
        if [[ "$file" == *.gz ]]; then
            zcat "$file"
        else
            cat "$file"
        fi
    done
}
